[luci-py] fix module object has no attribute RPCFailedError
http://screen/ZRgwmtPSQ70
```
AttributeError: 'module' object has no attribute 'RPCFailedError'
at _get_memory_usage (components/utils.py:101)
at dispatch_and_report (components/utils.py:137)
at __call__ (third_party/webapp2-2.5.2/webapp2.py:1529)
at __call__ (third_party/webapp2-2.5.2/webapp2.py:1535)
```

The module name was wrong. should be apiproxy_errors.RPCFailedError instead of runtime.
https://cs.corp.google.com/piper///depot/google3/apphosting/runtime/apiproxy_errors.py?type=cs&q=RPCFailedError&sq=package:piper+file://depot/google3+-file:google3/experimental&g=0&l=15

Bug: 1027407
Change-Id: If714cbaff8b75f8b2557b4ed9f21f9ec16c53628