Update patch set 5
Patch Set 5:

❯ ./swarming_bot/bot_code/task_runner_test.py TestTaskRunner.test_run_command_os_error   
F
======================================================================
FAIL: test_run_command_os_error (__main__.TestTaskRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./swarming_bot/bot_code/task_runner_test.py", line 443, in test_run_command_os_error
  File "./swarming_bot/bot_code/task_runner_test.py", line 255, in expectTask
AssertionError: "<The executable does not exist, a dependent library is missing or the command line is too long>\n<Check for missing .so/.dll in the .isolate or GN file or length of command line args>\n<Command: [u'/tmp/task_runnerufO0DF/w/ir/executable_that_shouldnt_be_on_your_system', u'thus_raising_OSError']>\n"

----------------------------------------------------------------------
Ran 1 test in 0.260s

FAILED (failures=1)

Does this change make an error?
It got fixed by reverting this change.

Patch-set: 5
Reviewer: Gerrit User 1366072 <1366072@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>