Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1: Commit-Queue+1
> > 
> > (2 comments)
> > 
> > Happens for commit-queue-dev now:
> > 
> > Could not load dynamic metadata for commit-queue-dev
> > ...
> > DynamicMetadataError: validation: patterns must be a list
> 
> It's still not clear to me why my app doesn't serve proper pattern. Have I forgotten some other "import _ magic"?

GAE entry point module (https://chromium.googlesource.com/infra/luci/luci-go/+/master/cq/appengine/frontend/main.go) in cq app doesn't import config package, and validation hooks thus are never registered.

Patch-set: 1
Reviewer: Gerrit User 1002539 <1002539@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>