[swarming] Skip unnecessary query for recent entities
As 2e22f0e139d68f0ae472a35f2292e01925c1c025 fixed completed_ts to always
be set, and this was made live everywhere in February 2019, we don't
need to run the query on more recent entities.

So only run the query when backfilling on older timestamp. This will
reduce the workload a bit.

Fix an invalid None check that was not working at all. This was causing
occasional error:
  AttributeError: 'NoneType' object has no attribute 'DESCRIPTOR'

Bug: 765435, 939204
Change-Id: I938e57967004a815f9a3c0ea97814bec37e95e3a