[isolateserver] Add a check that "files" is a dict when reading data
Sometimes isolateserver gives me a 500 when reading data, e.g.:
https://isolateserver.appspot.com/browse?namespace=default-gzip&digest=dced296489970a6f24e546ddea659be006d19d0a&as=files.json

According to the logs this is because there's a "files" field in some JSON
which is a list but is supposed to be a dict:

 File "handlers_frontend.py", line 287, in get
     json_data['files'].items(),
     AttributeError: 'list' object has no attribute 'items'

It looks like it's definitely supposed to always be a dict:
https://cs.chromium.org/chromium/infra/luci/client/isolated_format.py?l=448

Change-Id: Ia8c9fe95f7aaa3db2803657bcae7947662cadf40