[swarming] Reduced precision for approximately equals in `main_test.py`
I've noticed this fail a couple of times, most recent example:
- http://go/bbid/8788249366941083489

Specifically:

```
FAIL: test_attributes (main_test.SimpleMainTest)
...
      self.assertAlmostEqual(
      AssertionError: 0.4148789442274306 != 0.41487329644097226 within 5 places (5.647786458340409e-06 difference)
...
```

I checked how this value is actually calculated:
https://source.chromium.org/chromium/infra/infra/+/main:luci/appengine/swarming/swarming_bot/bot_code/task_runner.py;l=746;bpv=1

Since nothing has changed recently with this file I am uncertain of RC so reducing required precision to make this less common.

Change-Id: I1c1588e415ce44cb01eee85726cedb71090ef607