[swarming] Attempt to fix broken tests.
For some reason local_smoke_test started to import wrong `tools`
package, which eventually surfaces as delightfully informative
nose2 error:

=====================================================================
ERROR: test_not_found (nose2.loader.LoadTestsFailure)
---------------------------------------------------------------------
AttributeError: ... has not attribute 'ModuleImportFailure'

Maybe caused by

Traceback (most recent call last):

  File ".../nose2/util.py", line 165, in try_import_module_from_name
    module = __import__('.'.join(splitted_name))

ImportError: No module named ModuleImportFailure

Help it find the correct package.

R=iannucci@chromium.org, jonahhooper@google.com

Change-Id: Ia16e60a2eca23f6f3a542315b82ab75af4d27684