[swarming] fix test_run_command_os_error
https://crrev.com/c/1815455/5#message-eacb0447d657d5194da63c94ec562f0e54d06313

```
❯ ./swarming_bot/bot_code/task_runner_test.py TestTaskRunner.test_run_command_os_error
F
======================================================================
FAIL: test_run_command_os_error (__main__.TestTaskRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./swarming_bot/bot_code/task_runner_test.py", line 443, in test_run_command_os_error
  File "./swarming_bot/bot_code/task_runner_test.py", line 255, in expectTask
AssertionError: "<The executable does not exist, a dependent library is missing or the command line is too long>\n<Check for missing .so/.dll in the .isolate or GN file or length of command line args>\n<Command: [u'/tmp/task_runnerufO0DF/w/ir/executable_that_shouldnt_be_on_your_system', u'thus_raising_OSError']>\n"
```

Bug: 1006914
Change-Id: I54aba68a1b692c71123fc3d735a5e2d4f700a2c5