Update patch set 8
Patch Set 8:

(1 comment)

I updated to re-raise datastore_errors.BadValueError instead of ValueError.

I realized that six.raise_from doesn't inherit stacktrace, so changed to use six.reraise.
(It's bit annoying to extract stacktrace using sys.exc_info(), though.)
https://six.readthedocs.io/#six.reraise

```
WARNING:root:Incorrect new task request
Traceback (most recent call last):
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/swarming/handlers_endpoints.py", line 481, in new
    request_obj._pre_put_hook()
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/swarming/server/task_request.py", line 1349, in _pre_put_hook
    six.reraise(datastore_errors.BadValueError, e.message, tb)
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/swarming/server/task_request.py", line 1346, in _pre_put_hook
    auth.validate_realm_name(self.realm)
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/components/components/auth/api.py", line 2113, in validate_realm_name
    raise ValueError('Bad realm %r, want "<project>:<name>"' % (name,))
BadValueError: Bad realm u'test/invalid', want "<project>:<name>"
WARNING:root:Bad realm u'test/invalid', want "<project>:<name>"
Traceback (most recent call last):
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/components/components/auth/endpoints_support.py", line 174, in wrapper
    return func(service, *args, **kwargs)
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/components/components/auth/api.py", line 1925, in wrapper
    return func(*args, **kwargs)
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/swarming/handlers_endpoints.py", line 484, in new
    raise endpoints.BadRequestException(e.message)
BadRequestException: Bad realm u'test/invalid', want "<project>:<name>"
```

Patch-set: 8